version: "3.9"
services:
  postgres:
    container_name: localPostgresSQLDB2
    image: postgres
    environment:
      POSTGRES_DB: "local_db2"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5332:5432"
    networks:
      java17-network:
        aliases:
          - javaLibraryDB
networks:
  java17-network:
    name: 'our_java_library_network'